# Generated by Django 6.0.4 on 2026-04-08 09:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCreditTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive=credit added, negative=transferred out', max_digits=12)),
                ('transaction_type', models.CharField(choices=[('overpayment', 'Overpayment'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('adjustment', 'Adjustment')], max_length=20)),
                ('reference_type', models.CharField(blank=True, choices=[('payment', 'Payment'), ('fund_transfer', 'Fund Transfer'), ('manual', 'Manual')], max_length=20, null=True)),
                ('reference_id', models.PositiveIntegerField(blank=True, help_text='e.g. PaymentDetails id or CustomerFundTransfer id', null=True)),
                ('entry_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer_credit_transaction',
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('customer_name', models.CharField(max_length=200)),
                ('nid', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, help_text='Company reference ', max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\-\\s]{7,20}$', 'Invalid phone number')])),
                ('address', models.TextField(blank=True, null=True)),
                ('customer_type', models.CharField(choices=[('bw', 'Bandwidth'), ('soho', 'SOHO/Home')], max_length=20)),
                ('customer_number', models.CharField(blank=True, help_text='Auto-generated', max_length=50, null=True, unique=True)),
                ('contact_person', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('last_bill_invoice_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_master',
            },
        ),
        migrations.CreateModel(
            name='CustomerStatusFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], help_text='Customer status at time of feedback (from Customer Master)', max_length=20)),
                ('feedback_review', models.TextField(help_text='Service feedback or termination reason')),
                ('review_date', models.DateField(help_text='Date of feedback')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer_status_feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerStatusFeedbackRead',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer_status_feedback_read',
            },
        ),
        migrations.CreateModel(
            name='KAMMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('kam_name', models.CharField(max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'kam_master',
            },
        ),
        migrations.CreateModel(
            name='Prospect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\+?[0-9\\-\\s]{7,20}$', 'Invalid phone number')])),
                ('address', models.TextField(blank=True)),
                ('potential_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('contact_person', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=50)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, db_index=True, default='', help_text='Status managed by frontend (e.g., new, contacted, qualified, lost)', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'sales_prospects',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProspectAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='prospect_attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sales_prospect_attachments',
            },
        ),
        migrations.CreateModel(
            name='ProspectFollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateField()),
                ('notes', models.TextField(blank=True)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sales_prospect_followups',
                'ordering': ['-follow_up_date'],
            },
        ),
        migrations.CreateModel(
            name='ProspectStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=20)),
                ('to_status', models.CharField(max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'sales_prospect_status_history',
                'ordering': ['-changed_at'],
            },
        ),
    ]
