# Generated by Django 6.0.4 on 2026-04-08 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0002_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customercredittransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_credit_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customercredittransaction',
            name='invoice_id',
            field=models.ForeignKey(blank=True, db_column='invoice_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='bills.invoicemaster'),
        ),
        migrations.AddField(
            model_name='customermaster',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Auto-set to current user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customermaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, help_text='Auto-set to current user', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_customers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customercredittransaction',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='customers.customermaster'),
        ),
        migrations.AddField(
            model_name='customerstatusfeedback',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='Staff or system that created this feedback', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_customer_status_feedbacks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerstatusfeedback',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_feedbacks', to='customers.customermaster'),
        ),
        migrations.AddField(
            model_name='customerstatusfeedbackread',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_records', to='customers.customerstatusfeedback'),
        ),
        migrations.AddField(
            model_name='customerstatusfeedbackread',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_status_feedback_reads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customermaster',
            name='kam_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='customers.kammaster'),
        ),
        migrations.AddField(
            model_name='prospect',
            name='kam',
            field=models.ForeignKey(blank=True, help_text='Key Account Manager (KAM) assigned to this prospect', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prospects', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prospectattachment',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='customers.prospect'),
        ),
        migrations.AddField(
            model_name='prospectattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prospectfollowup',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='customers.prospect'),
        ),
        migrations.AddField(
            model_name='prospectstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prospectstatushistory',
            name='prospect',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='customers.prospect'),
        ),
        migrations.AddIndex(
            model_name='customercredittransaction',
            index=models.Index(fields=['customer_id'], name='customer_cr_custome_b47a56_idx'),
        ),
        migrations.AddIndex(
            model_name='customercredittransaction',
            index=models.Index(fields=['entry_date'], name='customer_cr_entry_d_b4c282_idx'),
        ),
        migrations.AddIndex(
            model_name='customerstatusfeedback',
            index=models.Index(fields=['customer'], name='customer_st_custome_6afaea_idx'),
        ),
        migrations.AddIndex(
            model_name='customerstatusfeedback',
            index=models.Index(fields=['status'], name='customer_st_status_e02feb_idx'),
        ),
        migrations.AddIndex(
            model_name='customerstatusfeedback',
            index=models.Index(fields=['review_date'], name='customer_st_review__e58e2a_idx'),
        ),
        migrations.AddIndex(
            model_name='customerstatusfeedback',
            index=models.Index(fields=['created_at'], name='customer_st_created_34dcbd_idx'),
        ),
        migrations.AddIndex(
            model_name='customerstatusfeedbackread',
            index=models.Index(fields=['user', 'is_read'], name='customer_st_user_id_d72611_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='customerstatusfeedbackread',
            unique_together={('feedback', 'user')},
        ),
    ]
