# Generated by Django 5.2.8 on 2026-04-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomerStatusFeedbackRead',
        ),
        migrations.DeleteModel(
            name='CustomerStatusFeedback',
        ),
    ]
