# Generated by Django 6.0.4 on 2026-04-08 09:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityInformationMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('terms_condition', models.TextField(blank=True)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('regards', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'utility_information_master',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UtilityDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('number', models.CharField(max_length=100)),
                ('branch', models.CharField(blank=True, max_length=200)),
                ('routing_no', models.CharField(blank=True, max_length=50)),
                ('swift_no', models.CharField(blank=True, max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('utility_master_id', models.ForeignKey(db_column='utility_master_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='utility.utilityinformationmaster')),
            ],
            options={
                'db_table': 'utility_details',
                'ordering': ['type', 'name'],
            },
        ),
    ]
