# Generated by Django 6.0.4 on 2026-04-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerEntitlementDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('bw', 'Bandwidth'), ('soho', 'SOHO/Home')], max_length=20)),
                ('mbps', models.DecimalField(blank=True, decimal_places=2, help_text='Only BW', max_digits=10, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Only BW - bandwidth prices (ipt,gcc,cdn,nix,baishan) stored here', max_digits=12, null=True)),
                ('last_changes_updated_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, help_text='Additional remarks or notes (e.g., bandwidth type for BW customers)', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_entitlement_details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerEntitlementMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('nttn_company', models.CharField(blank=True, max_length=200, null=True)),
                ('nttn_capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('link_id', models.CharField(blank=True, max_length=100, null=True)),
                ('nttn_uses', models.CharField(blank=True, max_length=100, null=True)),
                ('total_bill', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('type_of_bw', models.CharField(blank=True, help_text='Home only', max_length=50, null=True)),
                ('type_of_connection', models.CharField(blank=True, help_text='Home only', max_length=50, null=True)),
                ('connected_pop', models.CharField(blank=True, help_text='Home only', max_length=100, null=True)),
                ('last_bill_invoice_date', models.DateTimeField(blank=True, null=True)),
                ('zone_name', models.CharField(blank=True, help_text='Zone name for zone-based customer identification', max_length=200, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'customer_entitlement_master',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('sub_discount_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('type', models.CharField(choices=[('bw', 'Bandwidth'), ('soho', 'SOHO/Home')], default='bw', max_length=20)),
                ('mbps', models.DecimalField(blank=True, decimal_places=2, help_text='Only BW', max_digits=10, null=True)),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, help_text='Only BW - bandwidth prices (ipt,gcc,cdn,nix,baishan) stored here', max_digits=12, null=True)),
                ('last_changes_updated_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'invoice_details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceEmailSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name for this schedule', max_length=255)),
                ('enabled', models.BooleanField(default=True)),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('cron', 'Custom Cron')], default='daily', max_length=20)),
                ('run_at_hour', models.PositiveSmallIntegerField(default=9, help_text='Hour (0-23)')),
                ('run_at_minute', models.PositiveSmallIntegerField(default=0, help_text='Minute (0-59)')),
                ('weekly_day', models.PositiveSmallIntegerField(blank=True, default=0, help_text='Day of week for weekly: 0=Monday, 6=Sunday', null=True)),
                ('monthly_day', models.PositiveSmallIntegerField(blank=True, default=1, help_text='Day of month for monthly (1-31)', null=True)),
                ('cron_expression', models.CharField(blank=True, help_text='Custom cron: min hour day month dow (e.g. "0 9 * * *" for 9am daily)', max_length=100)),
                ('generate_invoices_before_send', models.BooleanField(default=True, help_text='Run invoice generation for target date before sending')),
                ('invoice_status_filter', models.CharField(choices=[('all', 'All invoices'), ('unpaid', 'Unpaid only'), ('partial', 'Unpaid and partial')], default='unpaid', max_length=20)),
                ('days_lookback', models.PositiveIntegerField(default=7, help_text='Only send invoices from the last N days')),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('next_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'invoice_email_schedule',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('issue_date', models.DateField()),
                ('total_bill_amount', models.DecimalField(decimal_places=2, default=0, help_text='Auto calculated', max_digits=12)),
                ('total_paid_amount', models.DecimalField(decimal_places=2, default=0, help_text='Auto calculated', max_digits=12)),
                ('total_balance_due', models.DecimalField(decimal_places=2, default=0, help_text='Auto calculated', max_digits=12)),
                ('total_vat_amount', models.DecimalField(decimal_places=2, default=0, help_text='Auto calculated', max_digits=12)),
                ('total_discount_amount', models.DecimalField(decimal_places=2, default=0, help_text='Auto calculated', max_digits=12)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, default='draft', max_length=20, null=True)),
                ('bill_number', models.CharField(blank=True, max_length=100, null=True)),
                ('activation_date', models.DateField(blank=True, null=True)),
                ('nttn_company', models.CharField(blank=True, max_length=200, null=True)),
                ('nttn_capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('total_bill', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('type_of_bw', models.CharField(blank=True, help_text='Home only', max_length=50, null=True)),
                ('type_of_connection', models.CharField(blank=True, help_text='Home only', max_length=50, null=True)),
                ('connected_pop', models.CharField(blank=True, help_text='Home only', max_length=100, null=True)),
                ('additional_entitlements', models.JSONField(blank=True, default=list, help_text='JSON array storing additional entitlement IDs and metadata for multi-entitlement invoices. Format: [{"id": 2, "bill_number": "BILL-00002", "zone_name": "Zone B"}, ...]', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'invoice_master',
                'ordering': ['-created_at'],
            },
        ),
    ]
