# Generated by Django 6.0.4 on 2026-04-08 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0001_initial'),
        ('customers', '0001_initial'),
        ('package', '0001_initial'),
        ('utility', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerentitlementdetails',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entitlement_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerentitlementdetails',
            name='package_master_id',
            field=models.ForeignKey(blank=True, db_column='package_master_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlement_details', to='package.packagemaster'),
        ),
        migrations.AddField(
            model_name='customerentitlementdetails',
            name='package_pricing_id',
            field=models.ForeignKey(blank=True, db_column='package_pricing_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entitlement_details', to='package.packagepricing'),
        ),
        migrations.AddField(
            model_name='customerentitlementdetails',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_entitlement_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerentitlementmaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entitlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerentitlementmaster',
            name='customer_master_id',
            field=models.ForeignKey(db_column='customer_master_id', on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='customers.customermaster'),
        ),
        migrations.AddField(
            model_name='customerentitlementmaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_entitlements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerentitlementdetails',
            name='cust_entitlement_id',
            field=models.ForeignKey(db_column='cust_entitlement_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='bills.customerentitlementmaster'),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='entitlement_details_id',
            field=models.ForeignKey(blank=True, db_column='entitlement_details_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_details', to='bills.customerentitlementdetails'),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='package_master_id',
            field=models.ForeignKey(blank=True, db_column='package_master_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_details', to='package.packagemaster'),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='package_pricing_id',
            field=models.ForeignKey(blank=True, db_column='package_pricing_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_details', to='package.packagepricing'),
        ),
        migrations.AddField(
            model_name='invoiceemailschedule',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_email_schedules', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoiceemailschedule',
            name='target_customer',
            field=models.ForeignKey(blank=True, help_text="If set, send only this customer's invoices. If null, send for all customers.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoice_email_schedules', to='customers.customermaster'),
        ),
        migrations.AddField(
            model_name='invoicemaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicemaster',
            name='customer_entitlement_master_id',
            field=models.ForeignKey(db_column='customer_entitlement_master_id', on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='bills.customerentitlementmaster'),
        ),
        migrations.AddField(
            model_name='invoicemaster',
            name='customer_master_id',
            field=models.ForeignKey(blank=True, db_column='customer_master_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='customers.customermaster'),
        ),
        migrations.AddField(
            model_name='invoicemaster',
            name='information_master_id',
            field=models.ForeignKey(blank=True, db_column='information_master_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='utility.utilityinformationmaster'),
        ),
        migrations.AddField(
            model_name='invoicemaster',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_invoices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='invoicedetails',
            name='invoice_master_id',
            field=models.ForeignKey(db_column='invoice_master_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='bills.invoicemaster'),
        ),
    ]
