# Generated by Django 6.0.4 on 2026-04-08 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFundTransfer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('reference_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('transfer_date', models.DateField()),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'customer_fund_transfer',
                'ordering': ['-transfer_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerFundTransferLine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Negative=debit (source), Positive=credit (target)', max_digits=12)),
            ],
            options={
                'db_table': 'customer_fund_transfer_line',
                'ordering': ['transfer_id', 'amount'],
            },
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pay_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_id', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_details',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMaster',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('payment_date', models.DateField()),
                ('payment_method', models.CharField(help_text='e.g., Credit Card, Bank Transfer, Cash', max_length=50)),
                ('remarks', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'payment_master',
                'ordering': ['-payment_date'],
            },
        ),
    ]
