# Generated by Django 6.0.4 on 2026-04-08 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bills', '0002_initial'),
        ('customers', '0002_initial'),
        ('payment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerfundtransfer',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_fund_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customerfundtransferline',
            name='customer_id',
            field=models.ForeignKey(db_column='customer_id', on_delete=django.db.models.deletion.CASCADE, related_name='fund_transfer_lines', to='customers.customermaster'),
        ),
        migrations.AddField(
            model_name='customerfundtransferline',
            name='transfer_id',
            field=models.ForeignKey(db_column='transfer_id', on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='payment.customerfundtransfer'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payment_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='received_by',
            field=models.ForeignKey(blank=True, db_column='received_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payment_details', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmaster',
            name='created_by',
            field=models.ForeignKey(db_column='created_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentmaster',
            name='customer_entitlement_master_id',
            field=models.ForeignKey(db_column='customer_entitlement_master_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bills.customerentitlementmaster'),
        ),
        migrations.AddField(
            model_name='paymentmaster',
            name='invoice_master_id',
            field=models.ForeignKey(db_column='invoice_master_id', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bills.invoicemaster'),
        ),
        migrations.AddField(
            model_name='paymentmaster',
            name='received_by',
            field=models.ForeignKey(blank=True, db_column='received_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='received_payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='payment_master_id',
            field=models.ForeignKey(db_column='payment_master_id', on_delete=django.db.models.deletion.CASCADE, related_name='details', to='payment.paymentmaster'),
        ),
        migrations.AddField(
            model_name='customerfundtransfer',
            name='source_payment_master_id',
            field=models.ForeignKey(blank=True, db_column='source_payment_master_id', help_text='Payment whose overpayment credit is being transferred (single source only)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fund_transfers_sourced_from', to='payment.paymentmaster'),
        ),
    ]
