# Generated by Django 5.2.8 on 2026-04-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='resource',
            field=models.CharField(choices=[('users', 'Users'), ('customers', 'Customers'), ('prospects', 'Prospects'), ('bills', 'Bills'), ('dashboard', 'Dashboard'), ('reports', 'Reports'), ('settings', 'Settings'), ('logs', 'Logs'), ('role', 'Roles'), ('roles', 'Roles (Admin)'), ('entitlements', 'Entitlements'), ('entitlement_details', 'Entitlement Details'), ('invoices', 'Invoices'), ('payments', 'Payments'), ('payment_details', 'Payment Details'), ('ledger', 'Ledger'), ('packages', 'Packages'), ('package_pricing', 'Package Pricing'), ('utilities', 'Utilities'), ('kam', 'KAM'), ('audit', 'Audit')], max_length=50),
        ),
    ]
